apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: fortsa.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Keep Istio's data-plane up-to-date automatically
  displayName: fortsa
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - istio
  - data-plane
  - fortsa
  links:
  - name: Fortsa
    url: https://fortsa.domain
  maturity: alpha
  provider:
    name: istio-ecosystem
    url: https://github.com/istio-ecosystem
  version: 0.0.0
